---
output: html_document
---
A sine wave has the form $y(x) = A \sin({ax} + \phi)$, where *y(x)* is the amplitude as a function of position, *x*, along the *x*-axis, *A* is the maximum amplitude, *a* is the periodicity, and $\phi$ is a phase angle that shifts the sine wave's position along the *x*-axis. Note that the units of the *x*-axis are multiples of $\pi$.

#### What is the Superposition of Waves?

When two (or more) waves travel along the same axis, the result is a single wave that is the sum of the individual waves. This is the principle of superposition. Use the pop-up menu to select the sine wave. With the slider set to 0, the figure shows the sine wave $y(x) = \sin(x)$. Adjusting the slider adds a second, phase-shifted sine wave where $\phi = \frac{2\pi k}{10})$, and where *k* is an integer increment in the phase angle. Note that when $n = 5$ and $\phi = \pi$ the two sine waves are out-of-phase and their sum is zero for all values of *x*. 

#### Why is the Principle of Superposition Important?

One consequence of the principle of superposition is that we can generate interesting repeating waves by adding together a series of sine waves. You can explore this for three different types of waves---square, triangle, and sawtooth---using the controls on the right. Setting the slider to 0 shows the target wave form. Adjusting the slider for the number of sine waves shows that including more sine waves better approximates the desired wave form. The equation that describes this summation appears below each figure. There are three things to note about the properties of the individual waves:

* The amplitudes of individual waves are given by the term outside the summation and the first term inside the summation; the periodicity is included within the sine function.
* The sine waves that make up the triangle wave and the sawtooth wave switch between positive and negative amplitudes because of the term $(-1)^{k}$; for the square wave, all amplitudes are positive.
* The sine waves that make up the square wave and the triangle wave include odd positive integers only because of the term $(2k-1)$; for the sawtooth wave, the periodicities are all positive integers.

The ability to write an equation for a wave in terms of sine functions is interesting and a topic we will return to in the module on the Fourier transform.
