---
output: html_fragment
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

<!-- ```{=html} -->
<!-- <script type="text/x-mathjax-config"> -->
<!-- MathJax.Hub.Config({ -->
<!--   TeX: { -->
<!--     extensions: ["[Contrib]/mhchem/mhchem.js"] -->
<!-- } -->
<!-- }); -->
<!-- MathJax.Hub.Config({  -->
<!--         "HTML-CSS": { scale: 90 },  -->
<!--         SVG: { linebreaks: { automatic:true } },  -->
<!--  }); -->
<!-- </script> -->
<!-- ``` -->

<!-- text for introduction -->

A sine wave has the mathematical form $y(x) = A \sin({ax} + \phi)$, where $y(x)$ is the sine wave's amplitude as a function of its position, *x*, along the *x*-axis in units of $\pi$, where *A* is the sine wave's maximum amplitude, where *a* is its periodicity (or frequency), and where $\phi$ is a phase angle that shifts the sine wave's position along the *x*-axis. 

#### What is the Superposition of Waves?

When two (or more) waves travel in the same direction along the same axis, the result is a single wave that is the sum of the individual waves. This is the principle of superposition, which we illustrate here using the figure on the right. Each row shows two individual sine waves, identified as $y_1$ and $y_2$, and their sum, $y_3$, where $y_3 = y_1 + y_2$. 

* In the first row, the sine waves $y_1$ and $y_2$ are identical and equal to $\sin(x)$. Adding these waves together gives a new sine wave, $y_3$, that has the same periodicity, but an amplitude that is twice that of $y_1$ and $y_2$. 

* In the second row, one of the sine waves, $y_2$, is shifted by a phase angle of $\pi$ relative to the other sine wave, $y_1$. This places the two waves in direct opposition to each other, such that for every value of $x$, the amplitude of $y_1$ is equal in magnitude but opposite in sign to the amplitude of $y_2$; as a result, the sum of $y_1$ and $y_2$, $y_3$, has an amplitude of 0 for all values of $x$.

* In the third row, the periodicity of one sine wave, $y_2$, is twice that of the other sine wave, $y_1$, which doubles the number of oscillations. The sum of $y_1$ and $y_2$ gives a new wave, $y_3$, that exhibits a more complex repeating pattern.

The example in the last row is particularly interesting as it suggests that we can build a library of repeating patterns by adding together an appropriate set of sine waves.  
